"""Email delivery for daily reports — SMTP with a safe dev/mock fallback.

Credentials come from environment variables only and are never exposed to the
API or stored in the database. When SMTP configuration is incomplete the
sender runs in mock mode: the email is logged (without secrets) and the run
history records ``email_status="mocked"`` so nothing is silently faked.
"""

from __future__ import annotations

import logging
import os
import smtplib
import time
from dataclasses import dataclass
from email.message import EmailMessage

import markdown as md

logger = logging.getLogger(__name__)

RETRY_DELAYS_SECONDS: tuple[float, ...] = (1.0, 2.0, 4.0)


@dataclass(frozen=True)
class EmailSettings:
    mode: str  # "smtp" | "mock"
    host: str
    port: int
    username: str
    password: str
    sender: str
    starttls: bool

    @classmethod
    def from_env(cls) -> "EmailSettings":
        host = os.getenv("SMTP_HOST", "")
        port = int(os.getenv("SMTP_PORT", "587") or "587")
        username = os.getenv("SMTP_USERNAME", "")
        password = os.getenv("SMTP_PASSWORD", "")
        sender = os.getenv("SMTP_FROM", "") or username
        starttls = os.getenv("SMTP_STARTTLS", "true").lower() != "false"

        requested_mode = os.getenv("EMAIL_MODE", "").lower()
        smtp_complete = bool(host and sender)
        if requested_mode == "smtp" and not smtp_complete:
            logger.warning("EMAIL_MODE=smtp but SMTP config is incomplete; falling back to mock")
        mode = "smtp" if (requested_mode != "mock" and smtp_complete) else "mock"
        return cls(
            mode=mode,
            host=host,
            port=port,
            username=username,
            password=password,
            sender=sender,
            starttls=starttls,
        )


@dataclass(frozen=True)
class EmailSendResult:
    status: str  # "sent" | "mocked" | "failed"
    attempts: int
    error: str = ""


def render_report_email(subject: str, report_markdown: str) -> tuple[str, str]:
    """Return (plain_text, html) bodies for a markdown report."""
    plain_text = report_markdown
    html_body = md.markdown(report_markdown, extensions=["tables", "fenced_code"])
    html = (
        "<!DOCTYPE html><html><head><meta charset='utf-8'></head>"
        "<body style=\"font-family: -apple-system, Segoe UI, Roboto, sans-serif; "
        "max-width: 720px; margin: 0 auto; padding: 24px; color: #1a1a2e;\">"
        f"{html_body}"
        "<hr><p style='color:#888;font-size:12px'>Generated by ATLAS — "
        "open-source AI intelligence platform.</p>"
        "</body></html>"
    )
    return plain_text, html


class EmailSender:
    """Send report emails over SMTP with retry, or mock-deliver in dev."""

    def __init__(self, settings: EmailSettings | None = None) -> None:
        self.settings = settings or EmailSettings.from_env()

    def send(self, recipient: str, subject: str, report_markdown: str) -> EmailSendResult:
        if not recipient:
            return EmailSendResult(status="failed", attempts=0, error="No recipient configured")

        plain_text, html = render_report_email(subject, report_markdown)

        if self.settings.mode == "mock":
            logger.info(
                "Mock email delivery recipient=%s subject=%r chars=%s (SMTP not configured)",
                recipient,
                subject,
                len(report_markdown),
            )
            return EmailSendResult(status="mocked", attempts=1)

        message = EmailMessage()
        message["From"] = self.settings.sender
        message["To"] = recipient
        message["Subject"] = subject
        message.set_content(plain_text)
        message.add_alternative(html, subtype="html")

        last_error = ""
        attempts = 0
        for attempt, delay in enumerate([0.0, *RETRY_DELAYS_SECONDS], start=1):
            if delay:
                time.sleep(delay)
            attempts = attempt
            try:
                self._smtp_send(message)
                logger.info("Email sent recipient=%s attempt=%s", recipient, attempt)
                return EmailSendResult(status="sent", attempts=attempt)
            except (smtplib.SMTPException, OSError) as exc:
                last_error = f"{type(exc).__name__}: {exc}"
                logger.warning("Email send attempt %s failed: %s", attempt, last_error)

        return EmailSendResult(status="failed", attempts=attempts, error=last_error)

    def _smtp_send(self, message: EmailMessage) -> None:
        with smtplib.SMTP(self.settings.host, self.settings.port, timeout=30) as smtp:
            if self.settings.starttls:
                smtp.starttls()
            if self.settings.username and self.settings.password:
                smtp.login(self.settings.username, self.settings.password)
            smtp.send_message(message)
